'use strict';
// PUBLIC keys (SPKI, base64) that may sign entitlement tokens, keyed by `kid`. Rotation is additive:
// add the new key here, ship, then switch ENTITLEMENT_SIGNING_KID on the server; retire the old kid
// one token-lifetime later. Generated by scripts/keygen.mjs; the private halves live only in Supabase.
module.exports = {
  '2026-09': 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvgy18d1U0ma9EJtTAVW4Mpmw++OCevJRocdrZsQNTCUBQcd+YeqYqXOHtjgD3jlSgODINp+j5hw039bvw+rUnQ==',
};
